version: "3.0"

services:
  boilerpipe_api:
    build: {context: ./, dockerfile: Dockerfile}
    image: mdmxfry/boilerpipe-api
    env_file:
      - .env
    ports:
      - ${PORT}:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s